# Generated by Django 5.1.6 on 2025-02-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phụ đề')),
                ('image', models.ImageField(upload_to='slides/', verbose_name='Hình ảnh')),
                ('button_text', models.CharField(default='MUA NGAY', max_length=50, verbose_name='Nút CTA')),
                ('button_link', models.URLField(blank=True, null=True, verbose_name='Liên kết nút')),
            ],
        ),
    ]
