# Generated by Django 5.1.6 on 2025-02-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_alter_product_image_alter_slide_button_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='slide',
            name='button_link',
            field=models.URLField(blank=True, null=True, verbose_name='Liên kết nút'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='button_text',
            field=models.CharField(default='MUA NGAY', max_length=50, verbose_name='Nút CTA'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(upload_to='slides/', verbose_name='Hình ảnh'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phụ đề'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tiêu đề'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
