# Generated by Django 5.1.6 on 2025-03-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ')], default='male', max_length=10),
        ),
    ]
