# Generated by Django 5.1.6 on 2025-03-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ')], default='male', max_length=10),
        ),
    ]
